### ISSUE TITLE
Read PHP Version from files or accept parameter to silence errors

### ISSUE THREAD

**Issue by davidsneighbour** [wapmorgan/PhpCodeAnalyzer#9]
I have a tag like the following in my code defining the min-PHP-version required:

```
/**
 * ... license, intro and so on...
 *
 * PHP Version 7.2
 *
 * ... phpdocs ...
 */
```

phpca still complains about "non-built-in" extensions that are bundled for quite a while:

```
Used non-built-in extensions in your code:
- [filter] Data Filtering. This extension is bundled with php since PHP 5.2.0. Extension is available in pecl: filter.
- [curl] Client URL Library. This extension is bundled with php since PHP 4.0.2. Extension is available in pecl: curl.
- [json] JavaScript Object Notation. This extension is bundled with php since PHP 5.2.0. Extension is available in pecl: json.
- [spl] Standard PHP Library (SPL). This extension is bundled with php since PHP 5.0.0. Extension is available in pecl: spl.
- [pdo] PHP Data Objects. This extension is bundled with php since PHP 5.1.0. Extension is available in pecl: pdo.
```

Idea 1: ignore extensions that are bundled since the last official supported version (currently 5.6)
Idea 2: parse my comment (it seems to be official way to tell php version) and silence everything that is, in my example, bundled in PHP 7.2

**Comment by wapmorgan** [comment]
You can use flag `--since-version=<version> Only include extensions not included since version`

**Comment by davidsneighbour** [comment]
Thanks, that is working as expected.
